version: '3'
services:
  backend: 
    container_name: backend
    env_file:
      - ./backend/.env.example
    build: 
       context: ./backend
    working_dir: /app
    ports:
      - "4000:4000"
    networks:
      - demo
    depends_on:
      - db

      
  frontend: 
    container_name: frontend
    env_file:
      - ./frontend/.env.example
    build: 
       context: ./frontend
    working_dir: /app
    ports:
      - "3000:3000"
    networks:
      - demo

  db:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: unless-stopped
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    networks:
      - demo
    volumes:
      -  mysql-data:/var/lib/mysql
volumes:
  mysql-data:

networks:
  demo:
    driver: bridge