version: '3'
services:
  backend: 
    container_name: server
    env_file:
      - ./backend/.env.example
    build: 
       context: ./backend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
  db:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: unless-stopped
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      -  mysql-data:/var/lib/mysql
volumes:
  mysql-data:
