version: '3'
services:
  app: 
    image: nodeimage
    container_name: server
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

    environment:
      - PORT=3000
      - HOST=0.0.0.0
  db:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: unless-stopped
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      -  mysql-data:/var/lib/mysql
volumes:
  mysql-data:
